spring.application.name=SPMEI
spring.datasource.url=jdbc:mysql://localhost:3306/manager
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

server.port=8085

# Safe Browsing API
google.safebrowsing.apiKey=YOUR_GOOGLE_API_KEY

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL
spring.mail.password=YOUR_EMAIL_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true